### ISSUE TITLE
Cannot start olelo, ruby error

### ISSUE THREAD

**Issue by Supermathie** [minad/olelo#97]
I'm trying to spin up olelo and getting:

```
wiki@wiki:~$ OLELO_CONFIG=/shared/config/config.yml unicorn /var/www/olelo/config.ru
I, [2014-04-23T15:39:58.190834 #1339]  INFO -- : listening on addr=0.0.0.0:8080 fd=9
I, [2014-04-23T15:39:58.191022 #1339]  INFO -- : worker=0 spawning...
I, [2014-04-23T15:39:58.192059 #1339]  INFO -- : master process ready
I, [2014-04-23T15:39:58.192454 #1341]  INFO -- : worker=0 spawned pid=1341
I, [2014-04-23T15:39:58.192758 #1341]  INFO -- : Refreshing Gem list
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': /var/www/olelo/lib/olelo/application.rb:78: syntax error, unexpected tREGEXP_BEG, expecting keyword_do or '{' or '(' (SyntaxError)
      if on_error && http_accept? /html/
                                   ^
/var/www/olelo/lib/olelo/application.rb:267: syntax error, unexpected keyword_end, expecting end-of-input
    from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/www/olelo/lib/olelo.rb:32:in `<top (required)>'
    from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/www/olelo/config.ru:12:in `block in <main>'
    from /usr/local/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
    from /usr/local/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
    from /var/www/olelo/config.ru:1:in `new'
    from /var/www/olelo/config.ru:1:in `<main>'
    from /usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.8.2/lib/unicorn.rb:48:in `eval'
    from /usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.8.2/lib/unicorn.rb:48:in `block in builder'
    from /usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:760:in `call'
    from /usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:760:in `build_app!'
    from /usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:624:in `init_worker_process'
    from /usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:647:in `worker_loop'
    from /usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:521:in `spawn_missing_workers'
    from /usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:140:in `start'
    from /usr/local/lib/ruby/gems/2.0.0/gems/unicorn-4.8.2/bin/unicorn:126:in `<top (required)>'
    from /usr/local/bin/unicorn:23:in `load'
    from /usr/local/bin/unicorn:23:in `<main>'
E, [2014-04-23T15:39:58.402366 #1339] ERROR -- : reaped #<Process::Status: pid 1341 exit 1> worker=0
```

Ruby:
ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-linux]

Gems: 
olelo (0.9.15)
unicorn (4.8.2)

Not sure what to do to diagnose or fix.

**Comment by ari-fikri** [comment]
Had the same problem.
Did you resolve it?

**Comment by brendanokane** [comment]
Same issue on OS X.

**Comment by driehuis** [comment]
Pull request #100 has a workaround.
